---
title: "Codebook"
output: 
  html_document:
    toc: true
    toc_float: true
---

This page contains information on the four datasets analyzed within this group project. Details on its primary source, as well as variables definitions and units, are specified for each of them.

## Urban Green Spaces in NYC

#### Acknowledgment of Ownership

*The primary dataset was developed by The Nature Conservancy's New York City Program (Mike Treglia and Emily Maxwell) with contributions (data aggregation and additional support) from Timon McPhearson of The Urban Systems Lab at The New School, Eric Sanderson of The Wildlife Conservation Society, and Greg Yetman of CIESIN at Columbia University.*

Treglia, Michael L., McPhearson, Timon, Sanderson, Eric W., Yetman, Greg, & Maxwell, Emily Nobel. (2018). Green Roofs Footprints for New York City, Assembled from Available Data and Remote Sensing (Version 1.0.0) [Available here](https://github.com/tnc-ny-science/NYC_GreenRoofMapping/tree/master/greenroof_gisdata/CurrentDatasets). Zenodo. http://doi.org/10.5281/zenodo.1469674

#### Primary Dataset: Variables codebook

**ID and location data**

* `fid` - Unique identifier
* `address` - Address based on MapPLUTO, joined to the dataset based on bbl.
* `borough` - Borough abbreviation pulled from MapPLUTO.
* `ownertype` - Owner type field pulled from MapPLUTO (C: City ownership, M: Mixed city & private ownership, O: Other – owned by either a public authority or the state or federal government, P: Private ownership, X: Fully tax-exempt property that may be owned by the city, state, or federal government; a public authority; or a private institution; blank: Unknown (usually private ownership))
* `zonedist1` - Zoning District 1 type pulled from MapPLUTO.
* `longitude` - Longitude in decimal degrees.
* `latitude` - Latitude in decimal degrees.

**Urban Green Space data**

* `green_area` - Total area of the footprint of the green roof as per this data layer, in square meter, calculated using the projected coordinate system (EPSG 2263).
* `building_area` - Total area of the footprint of the associated building, in square meter, calculated using the projected coordinate system (EPSG 2263).
* `prop_gr` - Proportion (%) of the building covered by green roof according to this layer (gr_area/bldg_area).
* `cons_year` - Year the building was constructed, pulled from the Building Footprint data.
* `heightroof` - Height of the roof of the associated building, in meter, pulled from the Building Footprint Data.
* `groundelev` - Lowest elevation at the building level, in meter, pulled from the Building Footprint Data.

**NYC building identifier**

* `bin` - NYC Building ID Number based on overlap between green roof areas and a building footprint dataset for NYC from August, 2017. (Newer building footprint datasets do not have linkages to the tax lot identifier (bbl), thus this older dataset was used). The most current building footprint dataset should be available at: https://data.cityofnewyork.us/Housing-Development/Building-Footprints/nqwf-w8eh. Associated metadata for fields from that dataset are available at https://github.com/CityOfNewYork/nyc-geo-metadata/blob/master/Metadata/Metadata_BuildingFootprints.md.
* `bbl` - Boro Block and Lot number as a single string. This field is a tax lot identifier for NYC, which can be tied to the Digital Tax Map and PLUTO/MapPLUTO. Metadata for fields pulled from PLUTO/MapPLUTO can be found in the PLUTO Data Dictionary. All joins to this bbl were based on MapPLUTO version 18v1.


#### Aggregated Dataset : Variables codebook

The same authors provide an additional dataset aggregated at the City Council District, which is used for regression purposes.

* `coun_dist` - Unique Identifier for each City Council District
* `borough` -  Name of the borough containing the respective City Council District
* `num_greenroofs` - Number of Green Roofs Contained in the respective City Council District
* `green_area` - total area (square meters) of green roofs in each City Council District
* `num_bldgs_total` - Number of total buildings contained within the respective City Council District
* `building_area` - Total area (square meters) of buildings in each City Council District
* `prop_gbuild` - Proportion (%) of the buildings in each City Council District with a green roof
* `prop_gr` - Proportion (%) of the rooftop area (building footprint area) covered by green roof within each City Council District

## Temperature in NYC

The datasets to analyze the s
(NYC.gov)[https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/]. The full dataset came be found (Github)[https://github.com/nychealth/EHDP-data/tree/production/indicators]. 

#### Heat Vulnerability Index (NTA)

The heat vulnerability index dataset shows the community-level heat impacts due to extreme heat events. The data were collected from 188 neighborhoods across the 5 boroughs of NYC. 

The heat vulnerability index is on a 5-point scale, with 1 being the lowest risk and 5 being the highest risk. It is based on a statistical model that uses social and environmental factors, such as surface temperature, green space, air conditioning access, poverty, and Black population, to estimate the risk of heat-related death. The Black population was identified as the most excluded from heat resources. Residents who are at highest heat risk do not have or use air conditioning, are older or have chronic health conditions or serious mental illnesses.

The dataset used is a collection of data sources:
 - American Community Survey  (2013-2017 5-year estimates)
 - New York City Department of Parks and Recreation (2017)
 - U.S. Geological Survey LandSat (2018)
 - United States Census Housing and Vacancy Survey (2017)

#### Daytime Summer Surface Temperature

The daytime summer surface temperature dataset shows the surface temperatures of 188 neighborhood tabulation areas (NTAs) in New York City. NTAs  are neighborhoods that were created by the NYC Department of Planning by aggregating census tracts into 195 neighborhood-like areas. Some neighborhoods were combined to reach the minimum population of 15,000 per NTA.

The daytime surface temperature was collected in Fahrenheit and varies based on vegetative covering and materials that retain heat, such as paved roads, sidewalks, and buildings. Neighborhoods with higher temperatures are seen to have more heat-exacerbated deaths associated with extreme heat events. The data source is the U.S. Geological Survey.

NTAs were used because we were able to match the neighborhoods across the two datasets, Heat Vulnerability Index and Daytime Summer Surface Temperature

**`envo_health` data**

*`daytime_surface_temp` = daytime landsat thermal data on surface collected on July 17, 2018 (averaged spatially), Farenheit
*`heat_vulnerability_index` = score ranging from 1 (lowest risk) to 5 (highest risk)
*`neighborhood` = 188 neighborhood tabulation areas 
*`latitude`, `longitude` = coordinates of the neighborhood tabulation areas (Note: Some coordinates may not accurately represent the combined NTAs due to multiple neighborhoods being grouped together)
*`borough` = New York City boroughs
*`geo_id` = geography ID for this entry (coded in the original dataset)

**`envo_greenroof` data**

The `envo_greenroof` dataset shows the average green area, average daytime surface temperature, and average heat vulnerability index for each of the 5 boroughs in NYC. This dataset was created by taking the average of green area (calculated using the primary dataset) and merging it with the average of daytime surface temperature and average heat vulnerability index (calculated using the `envo_health` dataset). 

*`borough` = New York City boroughs
*`avg_total_ green_area` = average total area of the footprint of the green roof per Borough, in square meter
*`avg_daytime_temp` = average daytime surface temperature, Farenheits
*`avg_heat_index` = average heat vulnerability index score 

References

1. New York City Department of Health, Environment & Health Data Portal. "Climate" data. Heat vulnerability index (NTA). Accessed at "https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/data-explorer/climate/" on 12/06/2022.

2. New York City Department of Health, Environment & Health Data Portal. "Climate" data. Daytime summer surface temperature. Accessed at "https://a816-dohbesp.nyc.gov/IndicatorPublic/beta/data-explorer/climate/" on 12/06/2022.


## Asthma in NYC

The dataset provides data of the number and rate of asthma hospitalizations and emergency department (ED) visits in New York State. These data are presented by age groups, sex, month of year, and total population for 3 selected year intervals (ex. 2000-2002, 2001-2003, etc...). These data show only a small proportion of people who have asthma, those whose condition is serious enough to require an emergency department (ED) visit or hospital stay. Data show the number of asthma ED visits and hospitalizations rather than the number of patients who were admitted or seen for asthma related illness. For example, if a person was hospitalized twice they would be counted twice.

#### Asthma Age-Adjusted Hospitalization Rates

Rates are calculated as the number of asthma hospitalizations per 10,000 residents in 5-year age groups using age-specific weights based on the estimated 2008-2010 population. The maps show average asthma age-adjusted hospitalization rates for the selected three year period. Users can compare asthma hospitalizations across counties in the following regions: New York State (whole state), New York City, New York State Excluding New York City. Users can see more clearly the differences in asthma hospitalization rates between the remaining New York State counties when New York City counties are removed from the display.

#### Asthma Age-Adjusted Emergency Department Visit Rates

Rates are calculated as the number of asthma ED visits per 10,000 residents in 5-year age groups using age-specific weights based on the estimated 2008-2010 population. The maps show average asthma age-adjusted ED visit rates for the selected three year period. Users can compare asthma ED visits across counties in the following regions: New York State (whole state), New York City, New York State Excluding New York City. Users can see more clearly the differences in asthma ED visits rates between the remaining New York State counties when New York City counties are removed from the display.

#### Critical Variables

The following variables are present in the wrangeles and tidied `asthma_df` (and `asthma2_df`) dataframes:

* `borough` = New York City boroughs
* `indicator` = shows what metric `aa_rate10ky` stands for: either age adjusted ED Visits (see explanation above), age adjusted Hospitalizations (see explanation above), or a self-created Severity Metric (ED visits divded by Hospitalizations, only present in `asthma2_df`)
* `year` = year the measure was recorded
* `aa_rate10kpy` = value of indicator per 10k inhabitants per year within a given borough
* `count` = absolute value of indicator per year within a given borough 
* `daily_average` = absolute value of indicator per day within a given borough and year


## Income Tax Credits in NYC

The data used for this project comes from two different data sources: 

The first is the [EITC Data](https://data.ny.gov/Government-Finance/Earned-Income-Tax-Credit-EITC-Claims-by-Credit-Typ/6q7b-8vuf), provided by New York State Open Data. 

The second is [Population Estimates](https://www.nyc.gov/site/planning/planning-level/nyc-population/nyc-population-current-estimates.page), provided by the U.S. Census Bureau.

Once cleaned and optimized for use in this project, the variables of interest are as follows: 

`tax_year` (numeric): The tax year, from 1994 - 2020
`credit_type` (character): The type of credit received, either `City EITC`, `State EITC` or `Noncust. EITC`
`borough`(character): Borough of New York City, either `Bronx`, `Brooklyn`, `Manhattan`, `Queens`, or `Staten Island`
`number_of_claims`(numeric): The number of claims filed 
`boro_credit_total`(numeric): The total amount, in dollars, received in EITC credit
`average_credit`(numeric): The average dollar amount of the EITC credit
`popestimate` (numeric): The population estimate for each borough, from 2016-2018

